### ISSUE TITLE
Feature request - date and order number on each line

### ISSUE THREAD

**Issue by nericson** [hppanpaliya/Walmart-Invoice-Exporter#1]
Thank you for this plugin. It would be really useful, I think, if the order date and order number were included on each item line, and if no extra rows (order date, order number, order total) were included at the bottom of the XLSX file. The reason being that, in practice, I take all my orders and combine them into one file, then sort by description, in order to classify them into business expense and other categories. But I need the date and order number on each item so I can tell what receipt it belongs to after sorting. Really I wouldn't need column headings either, although those are not too difficult to remove when combining files.

**Comment by hppanpaliya** [comment]
Hi @nericson,

Thank you for your valuable feedback and feature request! I understand the importance of including the order date and number on each item line for easier file management and sorting. To implement this enhancement, you can modify the below portion of the code that handles appending order details at the bottom of the XLSX file.

Please replace the existing code segment in the `content.js` file:
```javascript
worksheet.addRow([]); // Add an empty row for better readability

// Previously adding order details at the bottom
let total = worksheet.addRow(["Order Total", Number(orderDetails.orderTotal.replace(/[^0-9.-]+/g, ""))]);
worksheet.addRow(["Order Number", orderDetails.orderNumber]).font = { ...productFontStyle, bold: true };
worksheet.addRow(["Order Date", orderDetails.orderDate]).font = { ...productFontStyle, bold: true };

// Setting font style and currency format for the order total row
total.eachCell(function (cell, colNumber) {
  cell.font = { ...productFontStyle, bold: true };
  cell.numFmt = "$#,##0.00";
});
```

With the following code:
```javascript
// Iterate over each row to append the order number and order date to each item row, starting from the second row
worksheet.eachRow(function (row, rowNumber) {
  if (rowNumber > 1) { // Ensures header row is not modified
    row.getCell(5).value = orderDetails.orderNumber; // Append order number to the 5th column
    row.getCell(6).value = orderDetails.orderDate;   // Append order date to the 6th column
  }
});
```

This update ensures each product line contains the order number and date, streamlining your process for combining and sorting orders.

Please let me know if you have any questions or need further assistance with this change!

I'm closing this issue for now, but feel free to reopen it or create a new one if you encounter any problems or have more suggestions.
